
services:
  db:
    image: pgrouting/pgrouting:15-3.3-3.4.1
    container_name: sppg_gis_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sppg_gis_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: ${IMAGE_NAME:-ghcr.io/tsaqifradhitya/spasial-basis-data-sppg}:latest
    container_name: sppg_gis_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/sppg_gis_db
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      - db

volumes:
  pgdata:
